"""Add screening/interview/review AI-generated flags to interview_designs

Lets the frontend tell "still on the default/placeholder content" apart from
"real AI-generated (or already poc-linked) content" per kind, so it can
auto-fill a kind exactly once on first arrival and never again — a later
manual edit is never silently overwritten by a re-generation.

Revision ID: 0100
Revises: 0099
Create Date: 2026-09-07

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0100"
down_revision: Union[str, None] = "0099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "interview_designs",
        sa.Column("screening_ai_generated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "interview_designs",
        sa.Column("interview_ai_generated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "interview_designs",
        sa.Column("review_ai_generated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Existing rows that already have real content (interview seeded from a
    # linked ai-recruitment-poc job, review already AI-generated by the old
    # synchronous GET-time call) shouldn't be silently re-generated the next
    # time someone opens that hiring request's interview design.
    op.execute(
        "UPDATE interview_designs SET interview_ai_generated = true "
        "WHERE jsonb_array_length(interview_sections) > 0"
    )
    op.execute(
        "UPDATE interview_designs SET review_ai_generated = true "
        "WHERE jsonb_array_length(review_sections) > 0"
    )


def downgrade() -> None:
    op.drop_column("interview_designs", "review_ai_generated")
    op.drop_column("interview_designs", "interview_ai_generated")
    op.drop_column("interview_designs", "screening_ai_generated")
