"""Seed data for the users table."""

from datetime import date

USER_SEEDS = [
    # ── Benched candidates (status="benched") ──
    {
        "emp_id": "EMP001",
        "email": "rahul.sharma@talentos.com",
        "personal_email": "rahul.sharma@gmail.com",
        "name": "Rahul Sharma",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543210",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 3, 15),
        "doe": None,
        "date_of_birth": date(1998, 5, 12),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP002",
        "email": "priya.patel@talentos.com",
        "personal_email": "priya.patel@yahoo.com",
        "name": "Priya Patel",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543211",
        "role": "Tech Lead",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2020, 7, 1),
        "doe": None,
        "date_of_birth": date(1995, 2, 28),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP003",
        "email": "amit.kumar@talentos.com",
        "personal_email": "amit.kr@outlook.com",
        "name": "Amit Kumar",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543212",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 1, 10),
        "doe": None,
        "date_of_birth": date(1999, 8, 15),
        "internship_duration": 3,
        "band": "B1",
    },
    {
        "emp_id": "EMP004",
        "email": "sneha.reddy@talentos.com",
        "personal_email": "sneha.reddy@gmail.com",
        "name": "Sneha Reddy",
        "status": "benched",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543213",
        "role": "Test Engineer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2021, 11, 20),
        "doe": None,
        "date_of_birth": date(1997, 4, 10),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP005",
        "email": "vikram.singh@talentos.com",
        "personal_email": "vikky.singh@gmail.com",
        "name": "Vikram Singh",
        "status": "benched",
        "user_type": "permanent",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543214",
        "role": "DevOps",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2021, 6, 5),
        "doe": None,
        "date_of_birth": date(1996, 11, 22),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP006",
        "email": "ananya.gupta@talentos.com",
        "personal_email": "ananya.gupta@yahoo.com",
        "name": "Ananya Gupta",
        "status": "benched",
        "user_type": "permanent",
        "designation": "UI/UX Designer",
        "department": "Design",
        "phone_number": "+91-9876543215",
        "role": "Designer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 9, 12),
        "doe": None,
        "date_of_birth": date(1998, 12, 5),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP007",
        "email": "arjun.nair@talentos.com",
        "personal_email": "arjun.nair@gmail.com",
        "name": "Arjun Nair",
        "status": "benched",
        "user_type": "contract",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543216",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 4, 1),
        "doe": None,
        "date_of_birth": date(2000, 3, 18),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP008",
        "email": "kavita.joshi@talentos.com",
        "personal_email": "kavita.joshi@outlook.com",
        "name": "Kavita Joshi",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Business Analyst",
        "department": "Product",
        "phone_number": "+91-9876543217",
        "role": "Analyst",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2021, 2, 14),
        "doe": None,
        "date_of_birth": date(1996, 7, 30),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP009",
        "email": "rohit.verma@talentos.com",
        "personal_email": "rohit.v@hotmail.com",
        "name": "Rohit Verma",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543218",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2019, 8, 22),
        "doe": None,
        "date_of_birth": date(1994, 9, 14),
        "internship_duration": None,
        "band": "B4",
    },
    {
        "emp_id": "EMP010",
        "email": "neha.agrawal@talentos.com",
        "personal_email": "neha.agrawal@gmail.com",
        "name": "Neha Agrawal",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543219",
        "role": "Developer",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2022, 5, 30),
        "doe": None,
        "date_of_birth": date(1999, 1, 25),
        "internship_duration": 6,
        "band": "B1",
    },
    {
        "emp_id": "EMP011",
        "email": "deepak.mishra@talentos.com",
        "personal_email": "deepak.mishra@gmail.com",
        "name": "Deepak Mishra",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Data Analyst",
        "department": "Data Science",
        "phone_number": "+91-9876543220",
        "role": "Analyst",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 2, 1),
        "doe": None,
        "date_of_birth": date(2000, 6, 8),
        "internship_duration": 3,
        "band": "B1",
    },
    {
        "emp_id": "EMP012",
        "email": "pooja.deshpande@talentos.com",
        "personal_email": "pooja.d@gmail.com",
        "name": "Pooja Deshpande",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543221",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 11, 15),
        "doe": None,
        "date_of_birth": date(1998, 10, 3),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP013",
        "email": "siddharth.rao@talentos.com",
        "personal_email": "sid.rao@yahoo.com",
        "name": "Siddharth Rao",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Technical Lead",
        "department": "Engineering",
        "phone_number": "+91-9876543222",
        "role": "Lead",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2018, 4, 10),
        "doe": None,
        "date_of_birth": date(1993, 3, 21),
        "internship_duration": None,
        "band": "B5",
    },
    {
        "emp_id": "EMP014",
        "email": "megha.choudhary@talentos.com",
        "personal_email": "megha.c@gmail.com",
        "name": "Megha Choudhary",
        "status": "benched",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543223",
        "role": "Test Engineer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 8, 5),
        "doe": None,
        "date_of_birth": date(1997, 12, 17),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP015",
        "email": "manoj.tiwari@talentos.com",
        "personal_email": "manoj.tiwari@outlook.com",
        "name": "Manoj Tiwari",
        "status": "benched",
        "user_type": "contract",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543224",
        "role": "DevOps",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 6, 1),
        "doe": None,
        "date_of_birth": date(2000, 9, 11),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP016",
        "email": "ishita.bose@talentos.com",
        "personal_email": "ishita.bose@gmail.com",
        "name": "Ishita Bose",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543225",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 3, 20),
        "doe": None,
        "date_of_birth": date(1999, 7, 4),
        "internship_duration": 6,
        "band": "B1",
    },
    {
        "emp_id": "EMP017",
        "email": "gaurav.saxena@talentos.com",
        "personal_email": "gaurav.sax@gmail.com",
        "name": "Gaurav Saxena",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543226",
        "role": "Developer",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2020, 1, 15),
        "doe": None,
        "date_of_birth": date(1995, 5, 19),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP018",
        "email": "ritu.jain@talentos.com",
        "personal_email": "ritu.jain@yahoo.com",
        "name": "Ritu Jain",
        "status": "benched",
        "user_type": "permanent",
        "designation": "HR Executive",
        "department": "Human Resources",
        "phone_number": "+91-9876543227",
        "role": "HR",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 4, 11),
        "doe": None,
        "date_of_birth": date(1997, 8, 29),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP019",
        "email": "harsh.pandey@talentos.com",
        "personal_email": "harsh.pan@hotmail.com",
        "name": "Harsh Pandey",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543228",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 7, 10),
        "doe": None,
        "date_of_birth": date(2000, 2, 14),
        "internship_duration": 3,
        "band": "B1",
    },
    {
        "emp_id": "EMP020",
        "email": "divya.iyer@talentos.com",
        "personal_email": "divya.iyer@gmail.com",
        "name": "Divya Iyer",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Product Manager",
        "department": "Product",
        "phone_number": "+91-9876543229",
        "role": "Manager",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2019, 11, 1),
        "doe": None,
        "date_of_birth": date(1994, 6, 9),
        "internship_duration": None,
        "band": "B4",
    },
    # ── Active employees (status="active") ──
    {
        "emp_id": "EMP021",
        "email": "suresh.k@talentos.com",
        "personal_email": "suresh.k@gmail.com",
        "name": "Suresh Kumar",
        "status": "active",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543230",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2021, 5, 10),
        "doe": None,
        "date_of_birth": date(1998, 3, 22),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP022",
        "email": "laxmi.n@talentos.com",
        "personal_email": "laxmi.n@yahoo.com",
        "name": "Laxmi Nair",
        "status": "active",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543231",
        "role": "Tech Lead",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2019, 9, 5),
        "doe": None,
        "date_of_birth": date(1995, 11, 12),
        "internship_duration": None,
        "band": "B4",
    },
    {
        "emp_id": "EMP023",
        "email": "vijay.m@talentos.com",
        "personal_email": "vijay.m@gmail.com",
        "name": "Vijay Menon",
        "status": "active",
        "user_type": "permanent",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543232",
        "role": "DevOps",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2020, 4, 17),
        "doe": None,
        "date_of_birth": date(1996, 8, 5),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP024",
        "email": "shweta.d@talentos.com",
        "personal_email": "shweta.d@outlook.com",
        "name": "Shweta Deshmukh",
        "status": "active",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543233",
        "role": "Test Lead",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2021, 3, 8),
        "doe": None,
        "date_of_birth": date(1997, 1, 30),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP025",
        "email": "karan.m@talentos.com",
        "personal_email": "karan.m@gmail.com",
        "name": "Karan Mehta",
        "status": "active",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543234",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2022, 2, 14),
        "doe": None,
        "date_of_birth": date(1999, 10, 8),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP026",
        "email": "nandini.r@talentos.com",
        "personal_email": "nandini.r@gmail.com",
        "name": "Nandini Rajan",
        "status": "active",
        "user_type": "permanent",
        "designation": "UI/UX Designer",
        "department": "Design",
        "phone_number": "+91-9876543235",
        "role": "Designer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2021, 10, 25),
        "doe": None,
        "date_of_birth": date(1998, 5, 16),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP027",
        "email": "prakash.g@talentos.com",
        "personal_email": "prakash.g@yahoo.com",
        "name": "Prakash Gupta",
        "status": "active",
        "user_type": "permanent",
        "designation": "Technical Lead",
        "department": "Engineering",
        "phone_number": "+91-9876543236",
        "role": "Lead",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2018, 6, 1),
        "doe": None,
        "date_of_birth": date(1993, 4, 20),
        "internship_duration": None,
        "band": "B5",
    },
    {
        "emp_id": "EMP028",
        "email": "aishwarya.s@talentos.com",
        "personal_email": "aishu.s@gmail.com",
        "name": "Aishwarya Srinivas",
        "status": "active",
        "user_type": "permanent",
        "designation": "Business Analyst",
        "department": "Product",
        "phone_number": "+91-9876543237",
        "role": "Analyst",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2022, 6, 20),
        "doe": None,
        "date_of_birth": date(1997, 9, 3),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP029",
        "email": "rajesh.k@talentos.com",
        "personal_email": "rajesh.k@hotmail.com",
        "name": "Rajesh Khanna",
        "status": "active",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543238",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2020, 3, 12),
        "doe": None,
        "date_of_birth": date(1995, 12, 25),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP030",
        "email": "tanvi.shah@talentos.com",
        "personal_email": "tanvi.shah@gmail.com",
        "name": "Tanvi Shah",
        "status": "active",
        "user_type": "permanent",
        "designation": "Data Scientist",
        "department": "Data Science",
        "phone_number": "+91-9876543239",
        "role": "Scientist",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2021, 8, 16),
        "doe": None,
        "date_of_birth": date(1996, 6, 7),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP031",
        "email": "ajay.p@talentos.com",
        "personal_email": "ajay.p@gmail.com",
        "name": "Ajay Pawar",
        "status": "active",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543240",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2023, 5, 5),
        "doe": None,
        "date_of_birth": date(2000, 11, 18),
        "internship_duration": 3,
        "band": "B1",
    },
    {
        "emp_id": "EMP032",
        "email": "shalini.g@talentos.com",
        "personal_email": "shalini.g@yahoo.com",
        "name": "Shalini Gokhale",
        "status": "active",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543241",
        "role": "Test Engineer",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2022, 10, 3),
        "doe": None,
        "date_of_birth": date(1998, 2, 28),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP033",
        "email": "mohit.ag@talentos.com",
        "personal_email": "mohit.ag@outlook.com",
        "name": "Mohit Agarwal",
        "status": "active",
        "user_type": "permanent",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543242",
        "role": "DevOps",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2021, 1, 11),
        "doe": None,
        "date_of_birth": date(1997, 7, 9),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP034",
        "email": "bhavna.tr@talentos.com",
        "personal_email": "bhavna.tr@gmail.com",
        "name": "Bhavana Trivedi",
        "status": "active",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543243",
        "role": "Developer",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2022, 12, 1),
        "doe": None,
        "date_of_birth": date(1999, 4, 15),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP035",
        "email": "dinesh.s@talentos.com",
        "personal_email": "dinesh.s@gmail.com",
        "name": "Dinesh Shetty",
        "status": "active",
        "user_type": "permanent",
        "designation": "Engineering Manager",
        "department": "Engineering",
        "phone_number": "+91-9876543244",
        "role": "Manager",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2017, 3, 1),
        "doe": None,
        "date_of_birth": date(1992, 8, 12),
        "internship_duration": None,
        "band": "B6",
    },
    {
        "emp_id": "EMP036",
        "email": "nikita.c@talentos.com",
        "personal_email": "nikita.c@gmail.com",
        "name": "Nikita Chopra",
        "status": "active",
        "user_type": "permanent",
        "designation": "HR Executive",
        "department": "Human Resources",
        "phone_number": "+91-9876543245",
        "role": "HR",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2023, 1, 22),
        "doe": None,
        "date_of_birth": date(2000, 12, 1),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP037",
        "email": "sagar.p@talentos.com",
        "personal_email": "sagar.p@yahoo.com",
        "name": "Sagar Patil",
        "status": "active",
        "user_type": "contract",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543246",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2023, 8, 14),
        "doe": None,
        "date_of_birth": date(2001, 3, 27),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP038",
        "email": "anita.r@talentos.com",
        "personal_email": "anita.r@hotmail.com",
        "name": "Anita Rao",
        "status": "active",
        "user_type": "permanent",
        "designation": "Product Manager",
        "department": "Product",
        "phone_number": "+91-9876543247",
        "role": "Manager",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2020, 6, 8),
        "doe": None,
        "date_of_birth": date(1995, 10, 20),
        "internship_duration": None,
        "band": "B4",
    },
    {
        "emp_id": "EMP039",
        "email": "vivek.b@talentos.com",
        "personal_email": "vivek.b@gmail.com",
        "name": "Vivek Bhatt",
        "status": "active",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543248",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "billable",
        "work_location_type": "home",
        "doj": date(2019, 5, 19),
        "doe": None,
        "date_of_birth": date(1994, 11, 5),
        "internship_duration": None,
        "band": "B4",
    },
    {
        "emp_id": "EMP040",
        "email": "reema.s@talentos.com",
        "personal_email": "reema.s@gmail.com",
        "name": "Reema Sen",
        "status": "active",
        "user_type": "permanent",
        "designation": "Data Analyst",
        "department": "Data Science",
        "phone_number": "+91-9876543249",
        "role": "Analyst",
        "work_mode": "hybrid",
        "delivery_status": "billable",
        "work_location_type": "office",
        "doj": date(2022, 7, 4),
        "doe": None,
        "date_of_birth": date(1998, 9, 10),
        "internship_duration": None,
        "band": "B2",
    },
    # ── Notice period employees (status="notice_period") ──
    {
        "emp_id": "EMP041",
        "email": "kiran.j@talentos.com",
        "personal_email": "kiran.j@gmail.com",
        "name": "Kiran Joshi",
        "status": "notice_period",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543250",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "transitioning",
        "work_location_type": "home",
        "doj": date(2021, 4, 1),
        "doe": date(2024, 6, 30),
        "date_of_birth": date(1998, 1, 8),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP042",
        "email": "monika.d@talentos.com",
        "personal_email": "monika.d@yahoo.com",
        "name": "Monika Das",
        "status": "notice_period",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543251",
        "role": "Developer",
        "work_mode": "hybrid",
        "delivery_status": "transitioning",
        "work_location_type": "office",
        "doj": date(2020, 2, 10),
        "doe": date(2024, 7, 15),
        "date_of_birth": date(1996, 5, 22),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP043",
        "email": "ravi.t@talentos.com",
        "personal_email": "ravi.t@hotmail.com",
        "name": "Ravi Teja",
        "status": "notice_period",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543252",
        "role": "Test Engineer",
        "work_mode": "remote",
        "delivery_status": "transitioning",
        "work_location_type": "home",
        "doj": date(2021, 9, 13),
        "doe": date(2024, 8, 1),
        "date_of_birth": date(1997, 6, 19),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP044",
        "email": "swati.p@talentos.com",
        "personal_email": "swati.p@gmail.com",
        "name": "Swati Phadke",
        "status": "notice_period",
        "user_type": "permanent",
        "designation": "UI/UX Designer",
        "department": "Design",
        "phone_number": "+91-9876543253",
        "role": "Designer",
        "work_mode": "remote",
        "delivery_status": "transitioning",
        "work_location_type": "home",
        "doj": date(2022, 3, 7),
        "doe": date(2024, 9, 1),
        "date_of_birth": date(1999, 2, 11),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP045",
        "email": "sumit.k@talentos.com",
        "personal_email": "sumit.k@gmail.com",
        "name": "Sumit Khanna",
        "status": "notice_period",
        "user_type": "permanent",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543254",
        "role": "DevOps",
        "work_mode": "remote",
        "delivery_status": "transitioning",
        "work_location_type": "home",
        "doj": date(2020, 11, 22),
        "doe": date(2024, 6, 15),
        "date_of_birth": date(1995, 9, 30),
        "internship_duration": None,
        "band": "B3",
    },
    # ── More benched candidates (status="benched") ──
    {
        "emp_id": "EMP046",
        "email": "anoop.s@talentos.com",
        "personal_email": "anoop.s@gmail.com",
        "name": "Anoop Shetty",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543255",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 9, 5),
        "doe": None,
        "date_of_birth": date(2000, 8, 16),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP047",
        "email": "pallavi.m@talentos.com",
        "personal_email": "pallavi.m@yahoo.com",
        "name": "Pallavi Mishra",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Senior Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543256",
        "role": "Developer",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2021, 7, 19),
        "doe": None,
        "date_of_birth": date(1996, 10, 3),
        "internship_duration": None,
        "band": "B3",
    },
    {
        "emp_id": "EMP048",
        "email": "girish.k@talentos.com",
        "personal_email": "girish.k@hotmail.com",
        "name": "Girish Kulkarni",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Technical Lead",
        "department": "Engineering",
        "phone_number": "+91-9876543257",
        "role": "Lead",
        "work_mode": "hybrid",
        "delivery_status": "available",
        "work_location_type": "office",
        "doj": date(2019, 1, 14),
        "doe": None,
        "date_of_birth": date(1993, 12, 8),
        "internship_duration": None,
        "band": "B5",
    },
    {
        "emp_id": "EMP049",
        "email": "asha.n@talentos.com",
        "personal_email": "asha.n@gmail.com",
        "name": "Asha Nambiar",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543258",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 8, 28),
        "doe": None,
        "date_of_birth": date(1998, 4, 25),
        "internship_duration": 6,
        "band": "B2",
    },
    {
        "emp_id": "EMP050",
        "email": "naveen.g@talentos.com",
        "personal_email": "naveen.g@gmail.com",
        "name": "Naveen Gowda",
        "status": "benched",
        "user_type": "contract",
        "designation": "Data Analyst",
        "department": "Data Science",
        "phone_number": "+91-9876543259",
        "role": "Analyst",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 10, 9),
        "doe": None,
        "date_of_birth": date(2001, 1, 14),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP051",
        "email": "jyoti.p@talentos.com",
        "personal_email": "jyoti.p@outlook.com",
        "name": "Jyoti Pandey",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543260",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 11, 20),
        "doe": None,
        "date_of_birth": date(2000, 5, 6),
        "internship_duration": 3,
        "band": "B1",
    },
    {
        "emp_id": "EMP052",
        "email": "akash.d@talentos.com",
        "personal_email": "akash.d@gmail.com",
        "name": "Akash Dasgupta",
        "status": "benched",
        "user_type": "permanent",
        "designation": "DevOps Engineer",
        "department": "Infrastructure",
        "phone_number": "+91-9876543261",
        "role": "DevOps",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 1, 17),
        "doe": None,
        "date_of_birth": date(1997, 3, 29),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP053",
        "email": "chitra.v@talentos.com",
        "personal_email": "chitra.v@gmail.com",
        "name": "Chitra Venkatesh",
        "status": "benched",
        "user_type": "permanent",
        "designation": "QA Engineer",
        "department": "Quality Assurance",
        "phone_number": "+91-9876543262",
        "role": "Test Engineer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 4, 25),
        "doe": None,
        "date_of_birth": date(1998, 7, 31),
        "internship_duration": None,
        "band": "B2",
    },
    {
        "emp_id": "EMP054",
        "email": "farhan.a@talentos.com",
        "personal_email": "farhan.a@yahoo.com",
        "name": "Farhan Ali",
        "status": "benched",
        "user_type": "permanent",
        "designation": "Software Engineer",
        "department": "Engineering",
        "phone_number": "+91-9876543263",
        "role": "Developer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2023, 5, 15),
        "doe": None,
        "date_of_birth": date(1999, 11, 9),
        "internship_duration": None,
        "band": "B1",
    },
    {
        "emp_id": "EMP055",
        "email": "zara.k@talentos.com",
        "personal_email": "zara.k@gmail.com",
        "name": "Zara Khan",
        "status": "benched",
        "user_type": "permanent",
        "designation": "UI/UX Designer",
        "department": "Design",
        "phone_number": "+91-9876543264",
        "role": "Designer",
        "work_mode": "remote",
        "delivery_status": "available",
        "work_location_type": "home",
        "doj": date(2022, 10, 10),
        "doe": None,
        "date_of_birth": date(1999, 6, 20),
        "internship_duration": 6,
        "band": "B2",
    },
]
