from enum import Enum


class ErrorCode(str, Enum):
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    DESIGNATION_NOT_FOUND = "DESIGNATION_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"


DEFAULT_PAGE_SIZE: int = 20
MAX_PAGE_SIZE: int = 100
