from enum import Enum


class ErrorCode(str, Enum):
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    DESIGNATION_NOT_FOUND = "DESIGNATION_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND"
    HIRING_REQUEST_NOT_FOUND = "HIRING_REQUEST_NOT_FOUND"
    HIRING_REQUEST_NOT_CREATED = "HIRING_REQUEST_NOT_CREATED"
    HIRING_REQUEST_NOT_UPDATED = "HIRING_REQUEST_NOT_UPDATED"
    HIRING_REQUEST_NOT_DELETED = "HIRING_REQUEST_NOT_DELETED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    EVALUATION_NOT_FOUND = "EVALUATION_NOT_FOUND"
    WEBHOOK_UNAUTHORIZED = "WEBHOOK_UNAUTHORIZED"
    WEBHOOK_INVALID_PAYLOAD = "WEBHOOK_INVALID_PAYLOAD"
    QUEUE_PUBLISH_FAILED = "QUEUE_PUBLISH_FAILED"
    SLOT_NOT_FOUND = "SLOT_NOT_FOUND"
    SLOT_INVALID_STATUS = "SLOT_INVALID_STATUS"
    SLOT_BOOKED = "SLOT_BOOKED"
    FORM_NOT_FOUND = "FORM_NOT_FOUND"
    ALERT_NOT_FOUND = "ALERT_NOT_FOUND"
    CALENDAR_NOT_CONFIGURED = "CALENDAR_NOT_CONFIGURED"
    CALENDAR_API_FAILED = "CALENDAR_API_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"


class EvaluationStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    SHORTLISTED = "SHORTLISTED"
    REJECTED = "REJECTED"
    INVALID = "INVALID"
    FAILED = "FAILED"


DEFAULT_PAGE_SIZE: int = 20
MAX_PAGE_SIZE: int = 100
